### ISSUE TITLE
Database entries

### ISSUE THREAD

**Issue by dziban303** [rikgale/VRSData#1]
So I'll just add aircraft with the missing/erroneous fields in the order in which they appear in aircraft.csv. I think it should be clear which items need adding/correction. 

# 2023-02-23
AE58EB / CNV-TEX2
AE27FE / USCG-H60
AE6A18 / 20-21102 / United States Army / PAT-H60

# 2023-02-24
AE11D8 / RCH-E3TF    # typo in op.code
AE14CE / CNV-T44
AE61C8 / CNV-F5
AE61C1 / 76-1532 / Northrop / Northrop F-5N Tiger II / serial L1007 / United States Navy / CNV-F5

**Comment by rikgale** [comment]
All updated - will end up in FullAircraft.tar.gz after 02:30 Zulu  25/02/23.
Format was really easy to use.
Thanks :)
