### ISSUE TITLE
B-52s

### ISSUE THREAD

**Issue by dziban303** [rikgale/VRSData#11]
As noted in the Discord, the ground truth of the registrations and serials are gonna be impossible to unwind without physically seeing the aircraft landing while broadcasting ADSB. Some sources agree, others disagree; none of them are especially trustworthy IMO. Instead, better to at least add the sides. Here are the hexes in the database which lack an operator code, which in all cases should be `RCH-B52`:

```prolog
AE56ED
AE586D
AE5871
AE5872
AE5873

AE5874
AE5875
AE5876
AE5877
AE5878

AE5879
AE587A
AE587B
AE587D
AE587E

AE5881
AE5882
AE5883
AE5885
AE588A

AE588C
AE588E
AE588F
AE5890
AE5892

AE5893
AE5894
AE5895
AE5896
AE5897

AE5898
AE5899
AE589B
AE589C
AE589D

AE589F
AE58A0
AE58A3
AE58A5
AE58A6

AE58A8
AE58A9
AE58AA
AE58AC
AE58AE

AE58B0
AE58B3
AE5970
```

**Comment by rikgale** [comment]
All done
Respect to the BUUFs!
Thanks for info
