### ISSUE TITLE
update rate slowing

### ISSUE THREAD

**Issue by dziban303** [rikgale/VRSData#25]
```j
#2023-03-27
AE63B7 / RCH-KC46BOOM
AE1E6F / CNV-TEX2

#2023-03-28
AE08BC / CNV-TEX2

#2023-03-30
AE4A1A / CNV-TEX2
AE1148 / CNV-TEX2
AE11EF / RCH-E3TF

AE61BF / reg 761528 / serial L1003
```

Also, `A4D979` should be a `CL30` I think:
```j
A4D979 / CL30 / Bombardier Challenger 300
```
I've submitted correction on the VRS SDM page so this will probably propagate down eventually, may not be worth changing it. Only mentioned because I submitted a request for a side (this is the Saints owner's plane), and want to avoid trouble of an incorrect filename if you choose to make it!

cheers

**Comment by rikgale** [comment]
Thanks for letting me know. VRS SDM data only end up in teh DB if I don't already have a populated line for the a/c.

I cross referenced this with rzjets and planebase. It would appear that the CL35 is correct, not CL30. The reg used to belong to a CL30, but that was sold in 2014 and replaced with a CL35 with the same reg.
![image](https://user-images.githubusercontent.com/66202012/228952239-a2a87174-e067-4935-bb29-01c89d5528eb.png)
 All others updated

**Comment by dziban303** [comment]
Well, FAA's N-number database says it's a `BD-100-1A10` which google told
me was a Challenger 300. I don't know anything about the plane or its
designation, I just assumed the FAA would have the correct information and
that google wouldn't steer me in the wrong direction, lol.

https://registry.faa.gov/AircraftInquiry/Search/NNumberResult?nNumberTxt=n411st

**Comment by rikgale** [comment]
It didn't steer you wrong, it was ambigous.
`BD-100-1A10` can also be a Challenger 350 - same as Challenger 300, but with different engines. (and a different ICAO Type Designator)
https://aviation-safety.net/database/types/Bombardier-BD-100-Challenger-300/specs

**Comment by dziban303** [comment]
Understood, thanks!

**Comment by rikgale** [comment]
Cool! It's splitting hairs, but if I don't complain, some other data nerd will ;)
