### ISSUE TITLE
mid-june

### ISSUE THREAD

**Issue by dziban303** [rikgale/VRSData#42]
```
ADFCBA / RCH-T1 (think you already did this guy)
ADFCAD / RCH-T1 (another_one.gif)

AE71DF / RCH-E3TF (Typo'd as ECH-E3TF)

ADFC77 / RCH-T1
AE5ECA / CNV-B06
AE5F0E / RCH-AC30J
ADFD0D / RCH-T1
AE14B9 / CNV-T44
```

**Comment by rikgale** [comment]
All done apart from the E3. Can you confirm the ICAO Hex for it as got it coming up blank in my DB.

**Comment by dziban303** [comment]
Whoops, all my fault. ae71df is a miscode of ae11df; i created the entry
locally *to avoid confusion in the future* and typo'd the type, thus
creating more confusion. 😩
cheers

**Comment by rikgale** [comment]
Ok, no worries :) Thanks for the updates
