### ISSUE TITLE
A P-8

### ISSUE THREAD

**Issue by dziban303** [rikgale/VRSData#43]
Man, been so long I forgot the format.

```
AE681F / Tactical / Boeing / P8 / Boeing P-8A Poseidon / United States Navy / CNV-P8A
```

This time it was 169567 as confirmed by a spotter when it landed—this aircraft has also used AE5F50 in the past, which is already in the database. So let's add AE681F as a tactical code.

```j
A65946 / Louisiana State Police

03E35F / ???? / Northrop / Northrop F-5N Tiger II / United States Navy / CNV-F5
```

**Comment by rikgale** [comment]
Checked and I did these ages ago and failed to close. Now closed. Thanks for updates
