### ISSUE TITLE
8 sept

### ISSUE THREAD

**Issue by dziban303** [rikgale/VRSData#50]
```j
AE58B7 / PAT-MC12
AE4864 / United States Army / PAT-H60
AE6911 / RCH-MC130J
AE5F14 / RCH-AC30J
AE0256 / RCH-C30J
AE73E7 / 170188 / AgustaWestland / A119 / AgustaWestland TH-73A Thrasher / United States Navy / CNV-A119
AE73ED / AgustaWestland / United States Marine Corps
AE73EE / 170195 / AgustaWestland / A119 / AgustaWestland TH-73A Thrasher / United States Marine Corps / CNV-A119
AE5EC0 / CNV-B06
AE093A / PAT-C560
AE14B8 / CNV-T44
AE1388 / RCH-C30J
AE5F14 / RCH-C30J
0D07D5 / ANX
```

These beech variants are such a mess.

ae73ed [appears to be](https://live.staticflickr.com/65535/52929647037_7fd11c604c_4k.jpg) a USMC bird rather than Navy, dunno if you think it's worth making a side for these (probably not). Pretty limited imagery of this type that I can find.

**Comment by rikgale** [comment]
I have done a side... the MARINE marking is so small on the back I was able to use the navy version and tweak a few pixels and add USMC and the seal.
Thanks for all the additions.
