### ISSUE TITLE
october

### ISSUE THREAD

**Issue by dziban303** [rikgale/VRSData#51]
```j
AE683E / Tactical / Boeing / P8 / Boeing P-8A Poseidon / United States Navy / CNV-P8A

```

**Comment by rikgale** [comment]
All done, but I'll leave open for a bit incase you find anything else. As always - Many thanks!

**Comment by dziban303** [comment]
Yeah I've got another one here and I'm sure a few more will pop up

```j
AE567A / United States Army / PAT-H60 
```

**Comment by dziban303** [comment]
Got some that are causing problems in a tool I'm using because some fields in the CSV contain commas or newlines.

* A4E15B, owner is `Airborne Imaging, Inc.`, can we change to `Airborne Imaging Inc.`
* 447AC7, owner is `FFMUNT, Untersber, Austria`, perhaps change to `FFMUNT - Untersber Austria` or something? 
* 43EA4C, there's an issue with the csv file where the RegisteredOwners field apparently has the company, TruJet, placed twice, with a newline between them: (note word wrapping is off, the line should go off the screen to the left)

![image](https://github.com/rikgale/VRSData/assets/7931765/9b809745-bab5-4b3a-8613-38d83c9f1771)

So the owner field should be fixed to just `Trujet`
![image](https://github.com/rikgale/VRSData/assets/7931765/74c9b3d4-7979-4164-b0f0-5e2b63ebe737)

**Comment by rikgale** [comment]
All done.
Cheers :)

**Comment by dziban303** [comment]
```j
A5E9ED / Plaquemines Parish Sheriff's Office
AC0A69 / RCH-U28  # is there a special side for 'AFSOC' U-28s?
AE0418 / CNV-E6
AE586E / 60-0003 / Boeing / B52 / Boeing B-52H Stratofortress / United States Air Force / RCH-B52
# typos in flagcode:
AE1389 / RCH-C30J  
AE0234 / RCH-KC10BOOM
AE0582 / RCH-C5M
AE07D7 / RCH-C17
AE54C6 / RCH-CH130J
B191D8 / RCH-E3TF # wrong hex, see below
43C09B / RFR-GLEX
43C4D9 / RFR-H47
405357 / NVY-AS65
43C0F7 / NVY-HAWKT1
3B7781 / CTM-A342   # no actual side for this yet, maybe just go with CTM
3B7782 / CTM-A342   # no actual side for this yet, maybe just go with CTM
```

`B191D8` has the wrong hex, it should be `AE11D8`, and it should be `RCH-E3TF`

I searched the OperatorFlagCode field for `^RCH[A-Za-z0-9]` which should find everything with a typo'd flagcode like `RCHC5M`. Did that for RCH, PAT, CNV, USMC, USCG, RFR, NVY, AAC, CFC, and CTM. The ones I found are above.

**Comment by rikgale** [comment]
Thanks. Not as many as I would have expected. :) The RCHC5M etc is a hold over from when I used to use someone elses side views and I have been changing them as I come across them. Not stumbled on any in ages and some of them I know are for a/c that are no longer flown. e.g. 43C0F7 used to be based down the road, but was retired last year. I'll update for consistency anyway. Cheer for finding the rest of them.

**Comment by rikgale** [comment]
is there a special side for 'AFSOC' U-28s? - no, not yet. The AFSOC is a place holder, but if you are happy to it to go under RCH-U28 then I'll stick with that.

**Comment by dziban303** [comment]
Yeah it should probably just go under RCH-U28

**Comment by dziban303** [comment]
```j
A3E916 / US Department of the Interior
AE14A3 / CNV-T44
```

Actually these are kind of all over the place. Some are `US Department of the Interior`, some are `United States Department of the Interior`, at least one (A97C0C) is `United States Department of Interior`. Which is best? I don't think anyone will misunderstand the abbreviated US so I'd go with that to save space

---

```j
AE4D9B / PAT-UV18
AC0A69 / RCH-U28 # don't forget this guy
AE1447 / RCH-C30J
```

**Comment by rikgale** [comment]
I have made these changes and also changes some of the US Department of the Interior ones... I did a search for interior as operator, and bacause I am working remotely, I got the ones I have picked up in the last 7 days. All of these have been normalised to US Department of the Interior

**Comment by dziban303** [comment]
```j
A638AD / City of New Orleans # typo in owner name

AE5B6E / RCH-U28
```

**Comment by rikgale** [comment]
All done. Closing for Octobers. Thanks for all the tweaks
