### ISSUE TITLE
unicode issues

### ISSUE THREAD

**Issue by dziban303** [rikgale/VRSData#53]
The unicode saga from the Discord server. `FullAircraft.csv` has broken unicode characters. The problem comes from the `RegisteredOwners` field in `BaseStation.sqb` for the following aircraft:

```j
111001 / PR-GAB / AB Promocoes E Producoes Artísticas E Gravadora Ltda

A5C122 / PR-NAF / True Participações Societárias Eireli

A028D2 / PT-WSJ / AB Promocoes E Producoes Artísticas E Gravadora Ltda

A3137D / PP-ASD / Tecno Indústria E Com De Computadores Ltda
```

The fields show up as binary blobs in `BaseStation.sqb`:
![image](https://github.com/rikgale/VRSData/assets/7931765/e5be057c-f17a-49df-854c-1adcdd417e32)

Replacing those fields with the corrected text shown above, saving the sqb, and exporting as CSV fixes the issue with the broken CSVs. Presumably this will work with scripts too.

**Comment by rikgale** [comment]
I look into this when back at PC. Thanks 👍

**Comment by rikgale** [comment]
Added in pre-processing of the input CSV to handle the borked encoding. Should pick up any future issues. Updated names will go out in tonights update.
