### ISSUE TITLE
january

### ISSUE THREAD

**Issue by dziban303** [rikgale/VRSData#55]
```j
AE6852 / Boeing / Boeing P-8A Poseidon   # mfg and type are wrong

A77AE7 / N581PC? # this a/c shows up in FAA N-number database as N581PC, we have it as 06-0581, not sure what to do
```

**Comment by rikgale** [comment]
Top one fixed

Bottom one - https://www.joebaugher.com/usaf_serials/2006.html - search for the reg (either of them). I'm gonna leave it as the Mil Reg.

**Comment by dziban303** [comment]
This one is in there as a T-38, it's a t-45
```j
AE62B5 / McDonnell Douglas / HAWK / McDonnell Douglas T-45C Goshawk / CNV-HAWK
AE67D2 / ???? / Boeing / United States Navy
AE67F8 / Boeing
AE67D5 / Boeing / CNV-P8A
AE67FB / CNV-P8A
```

We also have AE2BEF, which should be a Navy Seahawk. But going back to June 2021 it's been used by a Coastie HC-144, C2315, which *should* be AE4BEF, so looks like a miscode. Basically every hit in Radarbox and such shows it as using C2315 as its callsign, so if the MH-60R is still flying it hasn't been broadcasting ADSB.

Same thing for AE2BF2. This a/c should be using AE4BF2.

**Comment by rikgale** [comment]
Updated. I reset the two miscodes, so they might get flagged automatically if they are in the PlaneBase known list, if not I'll have to add them back by hand. We will only know after the next time I update.... probably Sunday.

**Comment by rikgale** [comment]
Right. The comments on DC confirm that these two USCG have no been added to the PB miscode list, so I will change them by hand. Should update for you overnight
