### ISSUE TITLE
Military aircraft updates since Feb 25

### ISSUE THREAD

**Issue by g0ldfngr** [rikgale/VRSData#9]
I will start with these and then once a week/month/when I remember I will query My updates of military chagnes in my db.  not sure how you want this formatted but here is the list I have in csv. my aircraft ID may be different from your database(you may know that already just wanted to be sure)
[military updates.csv](https://github.com/rikgale/VRSData/files/10902878/military.updates.csv)

**Comment by rikgale** [comment]
Thanks for this. I have had a whizz down the list and updated the flag codes on those that were missing in the master DB. Fleshed out a few NULL enteries and made side view for the USMC F5's Useful info. :) These updates should filter into the container in the next 24 hours - if yours is set to update
